Controllers/DocumentController.cs
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using studentTamu.Interface;
using studentTamu.Models;
using static System.Net.Mime.MediaTypeNames;

namespace studentTamu.Controllers
{
    public class DocumentController : Controller
    {
        private readonly IDocument document;
        private readonly IUser user;
        private readonly IWebHostEnvironment webHostEnvironment;

        public DocumentController(IDocument _document,IUser _user, IWebHostEnvironment _webHostEnvironment)
        {
            document = _document;
            user = _user;
            webHostEnvironment = _webHostEnvironment;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewBag.userData = user.UserList();
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Accounts");
            }
            
        }

        public string ResizeImage(SixLabors.ImageSharp.Image image, int maxWidth, int maxHeight)
        {
            if (image.Width > maxWidth || image.Height > maxHeight)
            {
                double widthRatio = (double)image.Width / maxWidth;
                double heightRatio = (double)image.Height / maxHeight;
                double ratio = Math.Max(widthRatio, heightRatio);

                int newWidth = (int)(image.Width / ratio);
                int newHeight = (int)(image.Height / ratio);

                return $"{newHeight},{newWidth}";
            }
            else
            {
                return $"{image.Height},{image.Width}";
            }
        }

        #region add document

        public IActionResult AddDocument(DocumentModel dm, IFormFile documentImg)
        {
            var uniqueU = new Guid();
            dynamic filename = "";
            if (documentImg != null && documentImg.Length > 0)
            {
                var file = documentImg;
                string dirUrl = webHostEnvironment.WebRootPath;
                string dirPath = Path.Combine(dirUrl, "image\\document");
                if (!Directory.Exists(dirPath))
                {
                    Directory.CreateDirectory(dirPath);
                }
                if (file.Length > 0)
                {

                    string filenameU = Path.GetFileName(documentImg.FileName.Trim('"'));
                    filename = uniqueU + filenameU;
                    string fullPath = Path.Combine(dirPath, filename);

                    using (var fileStream = SixLabors.ImageSharp.Image.Load(file.OpenReadStream()))
                    {
                        string newSize = ResizeImage(fileStream, 800, 800);
                        string[] aSize = newSize.Split(',');
                        fileStream.Mutate(a => a.Resize(Convert.ToInt32(aSize[1]), Convert.ToInt32(aSize[0])));
                        fileStream.Save(fullPath);
                    }

                }

                //save in database
                dm.dImage = filename;
                var data = document.InsertDocument(dm);
                return Json(data);
            }
            else
            {
                var data = document.InsertDocument(dm);
                return Json(data);
            }
        }

        #endregion

        #region list

        public IActionResult GetDocumentList()
        {
            var data = document.GetAllDocuments();
            return Json(data);
        }

        #endregion

        public IActionResult getDocumentById(int id)
        {
            var data = document.getDocumentById(id);
            return Json(data);
        }

        #region update

        public IActionResult UpdateDocument(DocumentModel dm, IFormFile documentUpdateImg,string deleteOldImage)
        {
            var uniqueU = new Guid();
            dynamic filename = "";
            if (documentUpdateImg != null && documentUpdateImg.Length > 0)
            {
                var file = documentUpdateImg;
                string dirUrl = webHostEnvironment.WebRootPath;
                string dirPath = Path.Combine(dirUrl, "image\\document");
                if (!Directory.Exists(dirPath))
                {
                    Directory.CreateDirectory(dirPath);
                }

                // Delete old image if it exists
                if (!string.IsNullOrEmpty(deleteOldImage))
                {
                    string oldImagePath = Path.Combine(dirPath, deleteOldImage);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                if (file.Length > 0)
                {

                    string filenameU = Path.GetFileName(documentUpdateImg.FileName.Trim('"'));
                    filename = uniqueU + filenameU;
                    string fullPath = Path.Combine(dirPath, filename);

                    using (var fileStream = SixLabors.ImageSharp.Image.Load(file.OpenReadStream()))
                    {
                        string newSize = ResizeImage(fileStream, 800, 800);
                        string[] aSize = newSize.Split(',');
                        fileStream.Mutate(a => a.Resize(Convert.ToInt32(aSize[1]), Convert.ToInt32(aSize[0])));
                        fileStream.Save(fullPath);
                    }

                }

                //save in database
                dm.dImage = filename;
                var data = document.UpdateDocument(dm);
                return Json(data);
            }
            else
            {
                var data = document.UpdateDocument(dm);
                return Json(data);
            }
        }

        #endregion

        public IActionResult deleteDocument(int id, string img)
        {
            string dirUrl = webHostEnvironment.WebRootPath;
            string dirPath = Path.Combine(dirUrl, "image\\document\\" + img);

            var targetPath = Path.Combine(dirPath);
            if (System.IO.File.Exists(targetPath.ToString()))
            {
                System.IO.File.Delete(targetPath);
            }
            var data = document.DeleteDocument(id);
            return Json(data);
        }

    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using studentTamu.Interface;

namespace studentTamu.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private readonly IStudent student;

        public StudentController(IStudent _student)
        {
            student = _student;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewBag.intRoleid = HttpContext.Session.GetInt32("intRoleid").ToString();
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Accounts");
            }
        }
        public IActionResult StudentPersonalDetailListData()
        {
            var data = student.StudentPersonalDetailList();
            return Json(data);
        }
        public IActionResult getStudentPersonalId(int studentId)
        {
            var data = student.getstudentPersonalDetail(studentId);
            return Json(data);
        }
        public IActionResult getEnglishListId(int studentId)
        {
            var data = student.evidenceOfEnglishList(studentId);
            return Json(data);
        }
        public IActionResult geEducationListId(int studentId)
        {
            var data = student.studentEducationList(studentId);
            return Json(data);
        }
        public IActionResult getExperienceListId(int id)
        {
            var data = student.studentExperienceLetterList(id);
            return Json(data);
        }
        public IActionResult deleteStudent(int studentId)
        {
            var data = student.DeleteStudent(studentId);
            return Json(data);
        }

    }
}

Controllers/StudentFormController.cs
using Microsoft.AspNetCore.Mvc;
using studentTamu.Interface;
using studentTamu.Models;

namespace studentTamu.Controllers
{
    public class StudentFormController : Controller
    {
        private readonly IStudentForm studentForm;

        public StudentFormController(IStudentForm _studentForm)
        {
            studentForm = _studentForm;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Accounts");
            }
        }

        #region Insert personal Detail
        public JsonResult AddPersonalDetailStudent(StudentFormModel sfm)
        {
            var data = studentForm.InsertStudentFormPersonalDetail(sfm);
            return Json(data);
        }
        #endregion

        #region Insert student education
        public JsonResult AddStudentEducation(StudentFormModel sfm)
        {
            dynamic data = string.Empty;

            foreach (var item in sfm.eduArrData)
            {
                sfm.pdID = item.pdID;
                sfm.degreeName = item.degreeName;
                sfm.institutionName = item.institutionName;
                sfm.academicGrading = item.academicGrading;
                sfm.marks = item.marks;
                sfm.dateOfCompletion = item.dateOfCompletion;

                data = studentForm.InsertStudentFormEducation(sfm);
            }
            return Json(data);
        }
        #endregion

        #region Insert student experience
        public JsonResult AddStudentExperience(StudentFormModel sfm)
        {
            dynamic data=string.Empty;

            foreach (var item in sfm.expArrData)
            {
                sfm.pdID = item.pdID;
                sfm.orgName = item.orgName;
                sfm.position = item.position;
                sfm.fromDate = item.fromDate;
                sfm.toDate = item.toDate;
                
                data = studentForm.InsertStudentFormExperience(sfm);
            }
            return Json(data);
        }
        #endregion

        #region Insert evidence of english
        public JsonResult AddStudentEnglishEvidence(StudentFormModel sfm)
        {
            var data = studentForm.InsertStudentFormEnglishEvidence(sfm);
            return Json(data);
        }
        #endregion
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using studentTamu.Interface;
using studentTamu.Models;
using System.Diagnostics.CodeAnalysis;

namespace studentTamu.Controllers
{
    public class UserController : Controller
    {
        private readonly IUser user;

        public UserController(IUser _user)
        {
            user = _user;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Accounts");
            }
        }
        #region user List
        public IActionResult UserList()
        {
            var data = user.UserList();
            return Json(data);
        }

        public IActionResult getUserById(int id)
        {
            var data = user.GetUserId(id);
            return Json(data);
        }

        public IActionResult updateUser(AccountsModel am)
        { 
            var data=user.UpdateUser(am);
            return Json(data);
        }

        public IActionResult DeleteUser(int id) 
        {
            var data=user.DeleteUser(id);
            return Json(data);
        }
        #endregion
    }
}

Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - studentTamu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/studentTamu.styles.css" asp-append-version="true" />

    <script src="~/Scripts/jquery/jquery.min.js"></script>
    <script src="~/Scripts/jquery/Jquery.ui.js"></script>
    <link href="~/Scripts/jquery/jquery-confirm.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery/jquery.validate.js"></script>
    <script src="~/Scripts/jquery/jquery.mask.min.js"></script>

    <link href="~/Scripts/toaster/toaster.min.css" rel="stylesheet" />
    <script src="~/Scripts/toaster/toaster.min.js"></script>
    <link href="~/Scripts/select2/Message.css" rel="stylesheet" />
    <link href="~/Scripts/select2/select2.css" rel="stylesheet" />
    <script src="~/Scripts/select2/select2.js"></script>
    <script src="~/Scripts/function/Function.js"></script>
    <script src="~/Scripts/function/multiple.js"></script>

    <!-- Custom fonts for this template-->
    <link href="~/Home/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Home/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />

</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <li>
                <!-- Sidebar - Brand -->
                <div class="row">
                    <div class="col-md-9">
                        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Home")">
                            <div class="sidebar-brand-icon rotate-n-15">
                                <i class="fas fa-laugh-wink"></i>
                            </div>
                            <div class="sidebar-brand-text mx-3">
                                Nirajan<sup>2</sup>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <div class="text-center d-none d-md-inline">
                            <button class="rounded-circle border-0" id="sidebarToggle" style="margin-left: -25px; margin-top: 13px"></button>
                        </div>
                    </div>
                </div>

                <!-- Divider -->
                <hr class="sidebar-divider my-0">
            </li>

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Home")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            @if (HttpContextAccessor.HttpContext.Session.GetString("role") == "Admin")
            {
                <li>
                    <!-- Divider -->
                    <hr class="sidebar-divider">

                    <!-- Heading -->
                    <div class="sidebar-heading">
                        Interface
                    </div>
                </li>

                <!-- Nav Item - Pages Collapse Menu -->
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Setting</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Users Info:</h6>
                        <a class="collapse-item" href="@Url.Action("Index","User")">User</a>
                        <a class="collapse-item" href="@Url.Action("RegisterUserIndex","Accounts")">Register</a>
                    </div>
                </div>
            </li>
            }

            <li>
                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Student Section
                </div>
            </li>

            <!-- Nav Item - Document -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Document")">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Document Upload</span>
                </a>
            </li>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Student</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Student Section:</h6>
                        <a class="collapse-item" href="@Url.Action("Index","Student")">Student Information</a>
                        <a class="collapse-item" href="@Url.Action("Index","StudentForm")">Student Form</a>
                    </div>
                </div>
            </li>


        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->                   

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <div class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small"
                                placeholder="Search for..." aria-label="Search"
                                aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                                </button>
                                </div>
                                </div>
                                </div>
                            </div>
                        </li>

                        <li>
                            <div class="topbar-divider d-none d-sm-block"></div>
                        </li>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@HttpContextAccessor.HttpContext.Session.GetString("username").ToString()</span>
                                <img class="img-profile rounded-circle"
                                     src="~/Home/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Tamu 2024</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you want to Log Out?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
               @*  <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div> *@

                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>

                    <form action="/Accounts/LogOff" method="post">
                    <button class="btn btn-danger" type="submit">Log Out</button>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Home/vendor/jquery/jquery.min.js"></script>
    <script src="~/Home/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Home/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Home/js/sb-admin-2.min.js"></script>

</body>
</html>